/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nosqltools;

import java.awt.Color;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author mgalea
 */
public class DeleteCollection extends javax.swing.JDialog {

    /**
     * Creates new form DeleteCollection
     */
    private final MainForm mainForm;
    
    public DeleteCollection(MainForm parent, boolean modal) 
    {
        super(parent, modal);
        this.mainForm = parent;
        initComponents();
        setCollectionsList();
        setDbNameLabel();
    }
    
    private void setCollectionsList()
    {
        DefaultListModel listModel = new DefaultListModel();
        List<String> availCollections = this.mainForm.dbcon.getAllCollections();
        
        for(String col : availCollections)
        {
            /**
             * We obviously don't want to drop system collections,
             * hence they are not added in the list...
             */
            if(!col.toLowerCase().contains(MongoReserved.SYSTEMCOLLECTIONSPREFIX))
            {
                listModel.addElement(col);
            }
        }
        
        collectionList.setModel(listModel);
    }
    
    private void setDbNameLabel()
    {
        this.dbNameLabel.setText(this.mainForm.dbcon.db.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        collectionList = new javax.swing.JList();
        executeDeleteButton = new javax.swing.JButton();
        dbdescLabel = new javax.swing.JLabel();
        dbNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Drop Collections ");
        setResizable(false);

        collectionList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(collectionList);

        executeDeleteButton.setText("Execute");
        executeDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeDeleteButtonActionPerformed(evt);
            }
        });

        dbdescLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dbdescLabel.setText("Collections of DB: ");

        dbNameLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        dbNameLabel.setText("Marco");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dbdescLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dbNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(executeDeleteButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbdescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(executeDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeDeleteButtonActionPerformed

        List<String> selectedCollections = collectionList.getSelectedValuesList();
        String dropMessage = Initializations.DROPCOLLETIONSMESSAGE;
        
        for(String collectionName : selectedCollections)
        {
            dropMessage += "\n\t\t" + collectionName;
        }
        
        JTextArea textMessage = new JTextArea(dropMessage);
        textMessage.setBorder(null);
        textMessage.setBackground(new java.awt.Color(214, 217, 223));
        textMessage.setEditable(false);
        
        int result = JOptionPane.showConfirmDialog(this, textMessage, Initializations.DROPCOLLECTIONTITLE, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        switch(result)
        {
            case 0: //The Confirmation button YES...
            {
                List<String> droppedCollections = this.mainForm.dbcon.dropCollections(selectedCollections);
                String droppedMessage = Initializations.DROPPEDCOLLECTIONSSUCCESSFULLY;
                
                for(String coll : droppedCollections)
                {
                    droppedMessage += "\n" + coll;
                }
                
                textMessage.setText(droppedMessage);
                refreshTreeView();
                JOptionPane.showMessageDialog(this, textMessage, Initializations.DROPCOLLECTIONSCOMMANDOUTPUT, JOptionPane.YES_OPTION);
                this.setVisible(false);
                break;
            }
            
            case 1: //The button NO...
            {
                break;
            }
            
            default:
                break;
        }
    }//GEN-LAST:event_executeDeleteButtonActionPerformed

    private void refreshTreeView()
    {
        DefaultTreeModel defTableMod = mainForm.dbcon.buildDBTree();
        if (defTableMod != null && mainForm.dbcon.isConnectionSuccess()) 
        {
            mainForm.jTree1.setModel(defTableMod);
            mainForm.Text_MessageBar.setText(Initializations.DBCONNSUCCESS);
            mainForm.Text_MessageBar.setForeground(Color.GREEN);
            mainForm.Menu_Collections.setEnabled(true);
            mainForm.addCollection.setEnabled(true);
        } 
        else 
        {
            mainForm.jTree1.setModel(null);
            mainForm.Text_MessageBar.setText(Initializations.DBCONNFAIL);
            mainForm.Text_MessageBar.setForeground(Color.RED);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DeleteCollection dialog = new DeleteCollection(new MainForm(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList collectionList;
    private javax.swing.JLabel dbNameLabel;
    private javax.swing.JLabel dbdescLabel;
    private javax.swing.JButton executeDeleteButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
